### ISSUE TITLE
Docker enhancement

### ISSUE THREAD

**Issue by zephylac** [GIScience/openpoiservice#64]
A little bit related to #63 

I found it quite annoying to connect `psql/postgis` database with `openpoiservice` when both are running in separated networks. I finally ended up using one `docker-compose.yml` for both openpoiservice and `psql/postgis`.

I understand it might frustrate people to force them using one docker image but in the other hand, when you end-up with ready-to-test solution it's quite satisfying.

Maybe we could had a demo `docker-compose.yml` or enhance the existing one ?

**Comment by TimMcCauley** [comment]
Yep, I find the idea of a demo docker-compose for those wanting to run it as "one" a good idea.

**Comment by zephylac** [comment]
My `docker-compose.yml` looks like that :

```
version: '2.2'

volumes:
 postgis-data:

services:
 gunicorn_flask:
  #network_mode: "host"
  build: .
  volumes:
  - ./osm:/deploy/app/osm
  - ./ops_settings_docker.yml:/deploy/app/openpoiservice/server/ops_settings.yml
  - ./categories_docker.yml:/deploy/app/openpoiservice/server/categories/categories.yml
  ports:
   - "5000:5000"
  mem_limit: 28g
  networks:
   - poi_network

 db:
  image: kartoza/postgis:11.0-2.5
  volumes:
   - postgis-data:/var/lib/postgresql
  environment:
   # If you need to create multiple database you can add coma separated databases eg gis,data
   - POSTGRES_DB=gis
   - POSTGRES_USER=gis_admin
   - POSTGRES_PASS=admin
   - POSTGRES_DBNAME=gis
   - ALLOW_IP_RANGE=0.0.0.0/0
   # Add extensions you need to be enabled by default in the DB. Default are the three specified below
   #- POSTGRES_MULTIPLE_EXTENSIONS=postgis,hstore,postgis_topology
  ports:
   - 5433:5432
  restart: on-failure
  healthcheck:
   test: "exit 0"
  networks:
   - poi_network

networks:
 bridge:
  driver: poi_network
```

I was too lazy to add backups like he did in [his `docker-compose.yml`](https://github.com/kartoza/docker-postgis/blob/develop/docker-compose.yml).
